### ISSUE TITLE
Bestbuy bot issue

### ISSUE THREAD

**Issue by X-I-O-N** [Yorisoft/puppet-purchase#7]
Hi, I successfully installed and run this on my pc but this is the issue I get when running the best buy script or the best buy test script

Environmnet: userInfo\_environment
processing.. /Navigating to signin page ..
processing.. |Signing in ..
processing.. \Signed in succesfully ..

[1/4] .. Navigating to listing page ..
processing.. \
TimeoutError: Navigation timeout of 30000 ms exceeded
processing.. /

**Comment by Yorisoft** [comment]
Hey @X-I-O-N, Happy to help. I actually just got back to managing the repo, been out of it for a bit. I just pushed a couple of updates and working on others atm. I would first try fetching the new changes, see if it helps. 

By the looks of it, it might be that it didn't actually  log in to the account and got hung up waiting for an html element. Also, any extra info like screenshots would help. I have it set up to capture screenshots for each bot, in this case it would be located in **record/screen_shots/bestbuy/**. 

Edit: Just need the last one that the bot took.

**Comment by Yorisoft** [comment]
Also,  I see that it is running in the 'Environmnet: userInfo_environment', I'm assuming you've filled out the required information in the **.env.userInfo** file, located in **scripts/<bot>/userInfo/.env.userInfo**. This is where the bot gets its user specific information, such as login info and listing url.

**Comment by X-I-O-N** [comment]
Yes I have edited my info in the env userinfo file. Attached are the images I get after I run the bestbuy bot test command. It still gives me the same error
![testUserInfo_2-6_63482+login_attempt](https://user-images.githubusercontent.com/29445658/110225099-232d4000-7e9f-11eb-8cba-66f0e33d34cf.png)
![testUserInfo_2-6_63482+start](https://user-images.githubusercontent.com/29445658/110225101-24f70380-7e9f-11eb-8528-5e67c1862d87.png)

**Comment by Yorisoft** [comment]
At the moment I think that it either did not log into the account or the url is not properly formatted, and thus it isnt navigating to the time listing page. Please cpy and paste here the url as you've defined it in the userInfo file. Here is an example of what it should look like. 
https://github.com/Yorisoft/puppet-purchase/blob/deec5f77c2dd54507ec4eaea70197a15d1aaebd1/scripts/bestbuy/user_info/.env.testUserInfo#L14

Edit: so the test command is also failing too..? Darn... If you're able to, once it's done logging in, see if you can click out of the blue pop up. If you do, then you can see if using a user account logged in or not regardless of what the output is.

**Comment by Yorisoft** [comment]
Does the terminal update to show that you've switched from using _userInfo to  _testUserInfo?

Also, just created a discord - feel free to hop on there
https://discord.gg/GBhXKv7S

**Comment by Yorisoft** [comment]
Hey @X-I-O-N, 

I haven't heard back from you, so I will be closing this issue. Feel free to reopen if you find it necessary. I've made a few changes to the program since we last spoke. One of the big changes being the **_removal of the test-user_**. Due to the account security that is associated with Gmail, and the bot detection that many of these sites are implementing, the test-user kept getting temp band from sites as well as getting prompted by Gmail to perform 2 step verification. 

I made the decision to remove my test-users from the repo but all the test are still there. This means you can create your own test-user and run any test by feeding in the test user information into the environment. 

export TEST_USER_EMAIL=
	   TEST_USER_PASSW=
	   TEST_USER_INBOX_PASSW=
	   TEST_USER_PHONE=
	   TEST_USER_LOC=
	   TEST_USER_CVV=
	   TEST_USER_LISTING_URL=
	
Use 'export' if you're on Linux or 'SET' if you're on Windows.  Refer to the readme file for more info
